/* eslint-disable no-console */
import { SchemaRegistry, type TransactionSigner, ZERO_ADDRESS } from "@ethereum-attestation-service/eas-sdk";
import "dotenv/config";
import { ethers } from "ethers";

import { eas, config } from "~/config";

/*
This file defines and registers the EAS schemas. 

Each schema's UID is generated by hashing the schema string, resolver address and revocable boolean.
This means applications and profiles share the same schema and are differentiated by the type.


Run: npx tsx src/lib/eas/registerSchemas
*/

const approvalSchema = "bytes32 type, bytes32 round";

const schemas = [{ name: "Voter Approval", schema: approvalSchema }];

// Map app chain names to Alchemy network identifiers
const ALCHEMY_NETWORKS: Record<string, string> = {
  ethereum: "mainnet",
  optimism: "optimism",
  optimismSepolia: "optimism-sepolia",
  arbitrum: "arbitrum",
  linea: "linea",
  sepolia: "sepolia",
  base: "base",
  baseSepolia: "base-sepolia",
};

const alchemyNetwork =
  ALCHEMY_NETWORKS[(process.env.NEXT_PUBLIC_CHAIN_NAME as string) || "optimismSepolia"] || "optimism-sepolia";

const provider = new ethers.AlchemyProvider(alchemyNetwork, process.env.NEXT_PUBLIC_ALCHEMY_ID);

const wallet = new ethers.Wallet(process.env.WALLET_PRIVATE_KEY!).connect(provider);

const schemaRegistry = new SchemaRegistry(eas.contracts.schemaRegistry);
schemaRegistry.connect(wallet as unknown as TransactionSigner);

export async function registerSchemas(): Promise<{ name: string; uid: string }[]> {
  return Promise.all(
    schemas.map(async ({ name, schema }) => {
      const uid = SchemaRegistry.getSchemaUID(schema, ZERO_ADDRESS, true);

      const exists = await schemaRegistry.getSchema({ uid }).catch(() => undefined);

      if (exists) {
        return { name, uid };
      }

      // Explicitly pass resolverAddress = ZERO_ADDRESS for deterministic UID
      const tx = await schemaRegistry.register({ schema, resolverAddress: ZERO_ADDRESS, revocable: true });
      await tx.wait();
      return { name, uid };
    }),
  ).then((registered) => {
    registered.forEach((schema) => {
      console.log(`  ${schema.name}: ${schema.uid}`);
    });

    return registered;
  });
}

registerSchemas().catch(console.log);
